// Portfolio
export const OPEN_PORTFOLIO_ITEM = 'OPEN_PORTFOLIO_ITEM'
export const CLOSE_PORTFOLIO_ITEM = 'CLOSE_PORTFOLIO_ITEM'
export const FILTER_PORTFOLIO_BY = 'FILTER_PORTFOLIO_BY'
export const LOAD_PAGE = 'LOAD_PAGE'
export const LOAD_PORTFOLIO_ITEMS = 'LOAD_PORTFOLIO_ITEMS'
